### ISSUE TITLE
frp更新到0.52.3了

### ISSUE THREAD

**Issue by cnsn521** [koho/frpmgr#107]
frp更新到0.52.3了，配置文件切换成toml了，大佬啥时候更新，已经点了star，等大佬的更新

**Comment by felixwann** [comment]
同问，官方说要放弃ini配置文件的写法了，学toml又得学习一会儿

**Comment by haoqwenie** [comment]
服务器端为0.53，而作者您的版本为0.51，一直连接不上，可能是因为配置文件从ini改成了toml？

**Comment by koho** [comment]
> 服务器端为0.53，而作者您的版本为0.51，一直连接不上，可能是因为配置文件从ini改成了toml？

与文件格式无关，请排查一下日志和网络问题

**Comment by haoqwenie** [comment]
日志没有错误，显示
2023/12/25 22:05:01 [I] [visitor_manager.go:77] [f651e6c6f48c8d52] gracefully shutdown visitor manager
2023/12/25 22:05:01 [I] [service.go:214] [f651e6c6f48c8d52] try to reconnect to server...
2023/12/25 22:05:01 [I] [service.go:301] [f651e6c6f48c8d52] login to server success, get run id [f651e6c6f48c8d52]
但是在网页面板上一直是offline

**Comment by weikangqi** [comment]
希望能支持新版本的frp

**Comment by ruchid123123** [comment]
日常催跟一下

**Comment by LucaLush** [comment]
It is opensource ,do it yourself , don't be lazy

**Comment by gzlearm** [comment]
已上传蓝奏云，20240218
https://learm.lanzn.com/b01445gde
密码:errs
![图](https://github.com/koho/frpmgr/assets/59413875/bf85a299-9608-4f76-830c-252493e349a4)
