### ISSUE TITLE
安装失败。

### ISSUE THREAD

**Issue by baoqihui** [koho/frpmgr#113]
安装失败，无限弹出此弹窗。
可能是因为历史安装过，未正确卸载干净。但现在安装过程弹出此问题无法解决。
已重试新建FRP/frpmgr.exe ，无效
<img width="499" alt="image" src="https://github.com/koho/frpmgr/assets/50536515/759129cf-af34-4c3b-9b60-5f10bbd5a3fe">

**Comment by koho** [comment]
可以试试用这个工具修复：
https://support.microsoft.com/zh-cn/windows/%E4%BF%AE%E5%A4%8D%E9%98%BB%E6%AD%A2%E7%A8%8B%E5%BA%8F%E5%AE%89%E8%A3%85%E6%88%96%E5%88%A0%E9%99%A4%E7%9A%84%E9%97%AE%E9%A2%98-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d
