### ISSUE TITLE
关于日志

### ISSUE THREAD

**Issue by uc22** [koho/frpmgr#14]
关于日志的一些小建议：
1、默认添加logs文件夹和.log文件，提供开关由用户勾选，一个个去自己配置感觉有点麻烦>_<
2、日志里把用户token打个码吧^_^

**Comment by koho** [comment]
关于第一点，你是希望能提供禁用自动填写日志文件的功能吗，日志应该是刚需吧，不用日志就看不到详细信息了。而第二点，用户登录用的token应该是不会记录到日志文件里的。
