### ISSUE TITLE
build.bat  编译报错

### ISSUE THREAD

**Issue by kingween** [koho/frpmgr#15]
执行 build.bat 报错：
[+] Rendering icons
[+] Building resources
llvm-rc: Error in VERSIONINFO statement (ID 1): 
FILEVERSION fields (4294967294) does not fit in 16 bits.

**Comment by koho** [comment]
**Version: 1.6.0**
[+] Rendering icons
[+] Building resources
[+] Patching files
...
执行脚本是否有输出第一行的版本信息？

**Comment by kingween** [comment]
执行之后是这样的，不知道是不是llvm-rc版本问题还是其他？
D:\frpmgr-master>build.bat
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Version: ~1
[+] Rendering icons
[+] Building resources
llvm-rc: Error in VERSIONINFO statement (ID 1):
FILEVERSION fields (4294967294) does not fit in 16 bits.

**Comment by kingween** [comment]
可以了，非常感谢！！
