### ISSUE TITLE
执行 /service 报错

### ISSUE THREAD

**Issue by kingween** [koho/frpmgr#16]
我看main.go代码中可以执行服务端 ，但是当我执行的时候报错了，是什么原因呢？ 

<img width="722" alt="image" src="https://user-images.githubusercontent.com/16068633/156188443-6fe4e069-78f0-4847-86f0-d148c6259e1d.png">

**Comment by kingween** [comment]
请问一下 InstallService 中创建win服务中有个参数 /service , 这个不是启动服务端的意思吗？为何启动的却是客户端，并且cmd中加入/service 会报上面的错误
<img width="667" alt="image" src="https://user-images.githubusercontent.com/16068633/156906594-3d9fe7e1-3213-4129-9d04-d5f58d8013a9.png">

**Comment by koho** [comment]
这个参数只是用来判断程序是否运行在win服务，加了这个参数程序就会调用 [StartServiceCtrlDispatcher](https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-startservicectrldispatchera)，你在cmd运行这个函数肯定就报错了

**Comment by koho** [comment]
最新代码可以自行判断是否运行在win服务，所以这个参数也移除了。项目目前没有调用 frps 的代码
