### ISSUE TITLE
新增认证方式支持user和metadatas.token

### ISSUE THREAD

**Issue by raydoom** [koho/frpmgr#171]
希望能新增认证方式，配置文件里面写法如下
```
user = "user1"
metadatas.token = "token1"
```
如果配置好frpc.toml，然后导入到frpmgr中，是可以成功使用的，并且编辑的时候，用户名那里会显示 user1，但是GUI里面没有输入metadatas.token的地方，认证标签页里面的token应该和metadatas.token不是一个东西，希望在GUI里面加一个输入框，能输入metadatas.token
<img width="351" alt="image" src="https://github.com/user-attachments/assets/ece28f49-8ae7-464f-9ca4-8a2450a0e838">

**Comment by koho** [comment]
高级/元数据

![20240724122551](https://github.com/user-attachments/assets/3b977937-bcdf-4e60-b194-79ff75a8f48c)

**Comment by raydoom** [comment]
知道了，感谢
