### ISSUE TITLE
如何卸载干净？

### ISSUE THREAD

**Issue by hotwa** [koho/frpmgr#172]
![1722491794644](https://github.com/user-attachments/assets/7e2e21ab-d021-41b7-b674-f34c40d77e88)
旧版卸载不了，影响新版无法安装？如何手动删除干净

**Comment by koho** [comment]
看下安装目录的文件是否完整，默认安装目录是C:\Program Files\FRP

**Comment by koho** [comment]
#31 看看是不是这个问题

**Comment by hotwa** [comment]
![1722493302860](https://github.com/user-attachments/assets/f92318f0-54b5-4253-9de9-a897f949bfde)

**Comment by hotwa** [comment]
> #31 看看是不是这个问题

并不是，我已经尝试手动创建了这个文件，但是还是一样的报错

**Comment by koho** [comment]
为了更好地定位问题，请按以下步骤生成日志：

1. 按 Win + R 打开运行，输入 powershell，在打开的窗口输入以下命令：

```powershell
Get-Package -ProviderName MSI -Name "FRP*" | FL | findstr ProductCode
```

回车执行后会有类似输出：

```
Metadata                   : {ProductCode}
                                 ProductCode="{xxx-xxx-xxx-xxx}" />
Meta                       : {{ProductCode}}
```

复制第二行 `{xx-xx-xx}` 这串字符。

2. 继续输入下面命令，注意替换 `{xx-xx-xx}` 为上面复制的内容：

```
msiexec /x {xx-xx-xx} /L*v frp.txt
```

此时会弹出卸载窗口，按照提示操作卸载，不论卸载是否成功，直到卸载流程关闭，才进行下一步。

3. 继续输入`notepad frp.txt`运行，将记事本显示的日志上传到这里。

**Comment by hotwa** [comment]
PS C:\Users\pylyz> Get-Package -ProviderName MSI -Name "FRP*" | FL | findstr ProductCode
Get-Package: Unable to find package providers (MSI).

**Comment by hotwa** [comment]
PS C:\Users\pylyz> Get-PackageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    3.0.0.1          Destination, ExcludeVersion, Scope, SkipDependencies, H…
PowerShellGet            2.2.5.0          PackageManagementProvider, Type, Scope, AllowClobber, S…

似乎并没有msi，我已经手动删除了目录，注册表信息可能没有删除

**Comment by hotwa** [comment]
![1722740524556](https://github.com/user-attachments/assets/7cd9b9c3-110b-4fb4-b606-1cfb89b0a49c)
这个注册表信息很奇怪？

**Comment by hotwa** [comment]
![1722740624629](https://github.com/user-attachments/assets/658bbf6e-d5f4-468e-b34b-76bdc0abe84b)

我想是否把这个注册表删除就好了，这个目录我看不存在

**Comment by hotwa** [comment]
已经重装系统

**Comment by koho** [comment]
> PS C:\Users\pylyz> Get-Package -ProviderName MSI -Name "FRP*" | FL | findstr ProductCode Get-Package: Unable to find package providers (MSI).

你应该用的是高版本的 PowerShell 7, 缺少 msi 这个模块
