### ISSUE TITLE
mac端支持

### ISSUE THREAD

**Issue by SunSi12138** [koho/frpmgr#26]
您好，我想在macOS上使用它，但是现在的版本只支持windows，我不熟悉go，是否能够直接编译一个macOS版本使用呢？因为似乎是与Windows绑定的界面？不能的话可以请教一下如何调用的frpc吗，另外在windows上的使用体验非常好，感谢

**Comment by koho** [comment]
本项目依赖于 Windows 的 API，无法在其他系统运行。关于 frp 的使用文档 https://github.com/fatedier/frp
