### ISSUE TITLE
安装无法完成

### ISSUE THREAD

**Issue by mengqingmeng** [koho/frpmgr#31]
之前是安装过的，突然发现软件没有了，再次安装，提示安装失败
![image](https://user-images.githubusercontent.com/15814592/221140837-80cbe51c-1628-4168-838e-0a01d322c707.png)

**Comment by koho** [comment]
应该是卸载旧版本失败了，你看一下安装目录 C:\Program Files\FRP，把文件列表贴出来看看有没有少哪个文件。

**Comment by mengqingmeng** [comment]
> 应该是卸载旧版本失败了，你看一下安装目录 C:\Program Files\FRP，把文件列表贴出来看看有没有少哪个文件。

提示失败后， 没有目录：C:\Program Files\FRP

**Comment by koho** [comment]
> > 应该是卸载旧版本失败了，你看一下安装目录 C:\Program Files\FRP，把文件列表贴出来看看有没有少哪个文件。
> 
> 提示失败后， 没有目录：C:\Program Files\FRP

你之前安装的位置是这个吗，看一下已安装的应用里面能不能找到 FRP 管理器。

**Comment by mengqingmeng** [comment]
> 

已安装的目录，还在（但是已经被我手动删除了），但是里面文件明显缺失。之后再安装就无法安装成功，并且没有任何文件生成（即使更改安装路径、使用管理员权限安装）

**Comment by koho** [comment]
旧版本卸载成功才能安装新的。文件缺失应该是被杀毒软件干掉了。之前的版本卸载时需要读取安装目录的文件，所以你把目录删了卸载就失败了（最新版本已优化，缺失文件也不影响卸载）。

你需要重新手动创建以下文件以使旧版本卸载成功：

C:\Program Files\FRP\frpmgr.exe

提示：可先新建文本文档 `frpmgr.txt`，然后再重命名为 `frpmgr.exe`。

**Comment by mengqingmeng** [comment]
> 旧版本卸载成功才能安装新的。文件缺失应该是被杀毒软件干掉了。之前的版本卸载时需要读取安装目录的文件，所以你把目录删了卸载就失败了（最新版本已优化，缺失文件也不影响卸载）。
> 
> 你需要重新手动创建以下文件以使旧版本卸载成功：
> 
> C:\Program Files\FRP\frpmgr.exe
> 
> 提示：可先新建文本文档 `frpmgr.txt`，然后再重命名为 `frpmgr.exe`。

谢谢，此方法解决问题
