### ISSUE TITLE
升级安装失败，卸载后再安装报错

### ISSUE THREAD

**Issue by baoqihui** [koho/frpmgr#35]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/50536515/222643017-d0ce6b4d-e5f6-4b60-8ab5-c8af0f38dbbc.png">

**Comment by koho** [comment]
参考 #31

**Comment by baoqihui** [comment]
> 参考 #31
依然不可以，在安装过程提示这个
<img width="491" alt="image" src="https://user-images.githubusercontent.com/50536515/222699317-101fae4d-c02e-4a1d-ba84-f55834f963ee.png">

**Comment by koho** [comment]
> > 参考 #31
> > 依然不可以，在安装过程提示这个
> 
> <img alt="image" width="491" src="https://user-images.githubusercontent.com/50536515/222699317-101fae4d-c02e-4a1d-ba84-f55834f963ee.png">

旧版本卸载成功了吗？在已安装的程序里面点卸载，不然分不清是卸载问题还是安装问题。

**Comment by Looomo** [comment]
注册表编辑器，在  计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products下搜索关键词frp，找到带有字段frp 管理器的注册表项，删掉注册表项所在的文件夹就行了
