### ISSUE TITLE
隧道列表显示异常

### ISSUE THREAD

**Issue by Rio813** [koho/frpmgr#43]
### 正常情况下，可以显示隧道。
![image](https://user-images.githubusercontent.com/105364148/224274113-0ec5ec10-289c-4df5-9a82-5e7a713012c5.png)

### 当把FRP管理器窗口从主显示器拖动到副显示器时，隧道会消失不见，需要重启应用才能看到。
![image](https://user-images.githubusercontent.com/105364148/224274210-5357ec5e-ccea-4ced-9f2a-fa2ab29ff248.png)

### 这是我的显示器配置
![image](https://user-images.githubusercontent.com/105364148/224274446-01168aef-9366-4a18-ac66-760a26d40e23.png)

_**非常感谢您开发的软件，它十分好用，帮助我解决了很多问题！！！**_

**Comment by koho** [comment]
你安装最新版本试试，我这边测试是正常的。

**Comment by Rio813** [comment]
**非常感谢您的测试！**

更新版本到v1.12.0后，我又经过几次试验，发现当两台显示器的缩放比例一致时，隧道列表显示正常。而当两者缩放比例不一致时，就会产生这种状况。当我当我将两台显示器缩放比例设置相同时，可以避免这种情况。

![image](https://user-images.githubusercontent.com/105364148/224465192-952b5306-23f9-42f6-96e7-7ea8003cfa09.png)

_另外如果这些信息有帮助的话：我的主显示器是笔记本显示器，分辨率为1920\*1080，刷新率为240hz，副显示器分辨率为2560\*1440，刷新率为144hz。副显示器使用HDMI线材进行拓展连接。_

**Comment by koho** [comment]
我测试了一下，除了刷新率，其他设置和你保持一样，也是使用不同的缩放比例，但依旧无法复现界面显示异常的情况。

我的测试系统版本是 Win 10 最新版 22H2；使用 typec 扩展坞的 HDMI 接口连接副屏（使用原生 typec 也测过没问题）；分辨率和缩放设置和你一样；刷新率都是 60 hz。以下是测试视频：

https://user-images.githubusercontent.com/18328389/224480894-b604d107-7b1c-4ec2-ad46-d8748e13725f.mp4

为排除自变量，你可以设置 60hz 刷新率试试。如果你有其他想法，欢迎随时交流。

**Comment by Rio813** [comment]
### 感谢您的回复 
排除了各种自变量，并经过一系列测试，我猜测可能和系统对应用程序的自动缩放有关。
**1.更改应用程序的打开方式，或者2.在windows设置中 _关闭_ 允许windwos尝试修复应用**，可以暂时解决这个问题。
目前来看暂时还没有其它朋友反馈这个异常，所以也有可能是我自身的环境问题，现在目前软件也可以正常使用。

----

![image](https://user-images.githubusercontent.com/105364148/224485153-06f35c04-e898-42c6-9e42-793ed08cc87e.png)

----

另外通过观察发现，拖动应用窗口在屏幕穿梭时，自动缩放会导致隧道列表消失。设置相同的缩放比例或者采取上文中的措施，应用程序就不会自动缩放并且隧道列表也不会消失。

参考资料：[https://zhuanlan.zhihu.com/p/164884137](url)

https://user-images.githubusercontent.com/105364148/224485533-aadc6946-c78a-45e5-ba95-4a17e6403879.mp4

**Comment by koho** [comment]
程序本身是支持 DPI 切换的，如果用第一种方法就相当于禁用了自适应缩放的功能了，只能说是妥协的做法了。话说回来，你视频中演示用的是很旧的版本了，你能用最新版本再录制一下吗。顺便说下 Windows 的版本号，我好参考一下。

**Comment by koho** [comment]
目前我这边能测出来的问题是 DPI 切换时侧边栏的宽度可能出现异常：

![side](https://user-images.githubusercontent.com/18328389/224494025-299e9c12-e650-4f8a-9468-e7f3b14a80e6.png)

**Comment by Rio813** [comment]
我之前没有注意到旧版本更新失败，误以为更新成功。

----
![image](https://user-images.githubusercontent.com/105364148/224525919-951919ea-1bab-4bc3-b42c-81ad6ab40c56.png)
----

修复并卸载旧版本并更新到最新版本后，问题消失。


----

![image](https://user-images.githubusercontent.com/105364148/224525885-e0f98e21-4def-41da-acb0-a7b36eaf3845.png)

----

**感谢您的帮助🥰，很抱歉因为我的疏忽造成不必要麻烦。😭**
