### ISSUE TITLE
在添加新的单条转发规则时，不重启全部的连接，避免对于连接实时性要求高的服务造成断连影响

### ISSUE THREAD

**Issue by djerryz** [koho/frpmgr#55]
在添加规则，点击确认后，似乎会断开重连，对于连接质量有要求的服务会因此受到影响，是否有方案能解决

**Comment by koho** [comment]
frp 是支持 [热重载](https://github.com/fatedier/frp#hot-reloading-frpc-configuration) 的，要能在界面实现有两个方案：

1. 只针对开启 frp 管理端口的配置，当编辑代理时调用 HTTP 接口重载。如果未配置管理端口，则重启整个服务。
2. 针对所有配置，建立管道，从界面端通过管道控制后台服务进行热重载。
