### ISSUE TITLE
请问frpmgr在Windows系统服务中的名称为何？

### ISSUE THREAD

**Issue by ricky50575** [koho/frpmgr#6]
我好像没有在Windows系统服务管理器中找到欸，大致浏览了代码也没找到服务名称：可能是我遗漏。还望您告知。

**Comment by koho** [comment]
服务名称是以`FRPC$+配置名称`命名的。

![image](https://user-images.githubusercontent.com/18328389/125299476-c44f6a00-e35b-11eb-9e3d-9b841b710c9b.png)
