### ISSUE TITLE
每次关机后，服务都会停止。

### ISSUE THREAD

**Issue by fusang1337** [koho/frpmgr#77]
我需要提供哪些日志？
目前的情况是已设置服务启动方式为自动，但开机后仍是停止，需要手动启动

**Comment by koho** [comment]
提供一下配置文件

**Comment by Takdrift** [comment]
@koho 作者你好，frpmgr这个软件非常好用，但目前碰到同样的问题，重启电脑后查看服务的确在运行，但是无法跟服务器建立连接，必须得手动进到软件界面，停止后再开启才能生效。后面突然有一天开机后不需要再手动操作了，这之后就一直能正常自启动并成功连接。但最近用另一台PC该问题复现，不知道问题的根源可能会在哪。希望能够提供一点解决的思路，感谢！

frpc.ini的配置都是按照模版来的，个人感觉可能跟配置文件无关。
