### ISSUE TITLE
与SakuraFrp不兼容

### ISSUE THREAD

**Issue by Eric-168** [koho/frpmgr#93]
https://github.com/ZeroDream-CN/SakuraFrp
和这个服务器版本不兼容，官方客户端测试没问题
日志
2023/10/09 13:08:58 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:09:03 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:09:08 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:09:13 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:09:18 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:09:23 [W] [service.go:133] login to server failed: EOF
2023/10/09 13:09:28 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:09:32 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:09:37 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:09:42 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:09:47 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:09:52 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:09:57 [W] [service.go:133] login to server failed: EOF
2023/10/09 13:10:03 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:10:08 [W] [service.go:133] login to server failed: EOF
2023/10/09 13:10:13 [W] [service.go:133] login to server failed: EOF
2023/10/09 13:10:18 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:10:23 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:10:28 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:10:34 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:10:38 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:10:43 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:10:48 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:10:53 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:10:57 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:11:02 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:11:07 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:11:12 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:11:16 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:11:22 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:11:27 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:11:32 [W] [service.go:133] login to server failed: EOF
2023/10/09 13:11:37 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:11:43 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:11:48 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:11:53 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:11:58 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:12:03 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:12:08 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:12:13 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:12:18 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:12:23 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:12:28 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:12:33 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:12:37 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:12:42 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:12:47 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:12:52 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:12:57 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:13:02 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:13:07 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:13:12 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:16:53 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:16:58 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:17:03 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:17:08 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:17:12 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:17:17 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:17:22 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:17:27 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:17:32 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:17:37 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:17:42 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:17:48 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:17:52 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:17:57 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:18:02 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:18:06 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:18:11 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:18:16 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:18:21 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:18:26 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:18:31 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:18:36 [W] [service.go:133] login to server failed: EOF
2023/10/09 13:18:41 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:18:46 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:18:51 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:18:56 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:01 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:06 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:11 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:16 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:20 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:25 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:30 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:35 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:40 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:44 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:49 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:54 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:19:59 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:20:04 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:20:09 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:20:13 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:20:18 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:20:23 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:20:28 [W] [service.go:133] login to server failed: session shutdown
2023/10/09 13:20:33 [W] [service.go:133] login to server failed: session shutdown

**Comment by koho** [comment]
你提到的项目属于二次开发，与原版变动较大，难以同时兼容。
